import json
import os

from groq import Groq

_client: Groq | None = None


def _get_client() -> Groq:
    global _client
    if _client is None:
        _client = Groq(api_key=os.environ.get("GROQ_API_KEY"))
    return _client


_SYSTEM_PROMPT = (
    "You are an AI content classifier. Analyze the text provided and assess how likely "
    "it is to have been generated by an AI model rather than written by a human.\n\n"
    "Return ONLY a JSON object with this exact format:\n"
    '{\"score\": X.XX}\n\n'
    "Where X.XX is a float between 0.0 and 1.0:\n"
    "- 0.0 = definitely human-written\n"
    "- 1.0 = definitely AI-generated\n\n"
    "Consider: uniformity of sentence structure, presence of hedging or filler phrases "
    "(\"it is important to note\", \"furthermore\", \"in conclusion\"), absence of personal "
    "voice or idiosyncratic word choices, and overall stylistic consistency. "
    "Do not include any explanation — only the JSON object."
)


def get_llm_score(text: str) -> float | None:
    """Return AI-likeness score 0.0–1.0, or None on parse failure. Raises on API/network error."""
    response = _get_client().chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": _SYSTEM_PROMPT},
            {"role": "user", "content": f"Text to analyze:\n---\n{text}\n---"},
        ],
        temperature=0.0,
        max_tokens=20,
    )
    raw = response.choices[0].message.content.strip()
    try:
        data = json.loads(raw)
        score = float(data["score"])
        return max(0.0, min(1.0, score))
    except (json.JSONDecodeError, KeyError, ValueError, TypeError) as e:
        print(f"[WARN] get_llm_score parse failure: {e!r} | raw={raw!r}", flush=True)
        return None


def classify(raw_score: float) -> tuple[str, float]:
    """Map raw_score to (attribution, confidence) per spec thresholds.

    MS3: called with signal_1_score.
    MS4: called with weighted raw_score = 0.6*s1 + 0.4*s2 — thresholds unchanged.
    """
    if raw_score >= 0.70:
        attribution = "likely_ai"
    elif raw_score <= 0.30:
        attribution = "likely_human"
    else:
        attribution = "uncertain"
    confidence = round(0.5 + abs(raw_score - 0.5), 4)
    return attribution, confidence


if __name__ == "__main__":
    from dotenv import load_dotenv

    load_dotenv()

    tests = [
        (
            "Clearly AI",
            (
                "Artificial intelligence represents a transformative paradigm shift in modern "
                "society. It is important to note that while the benefits of AI are numerous, "
                "it is equally essential to consider the ethical implications. Furthermore, "
                "stakeholders across various sectors must collaborate to ensure responsible "
                "deployment."
            ),
        ),
        (
            "Clearly human",
            (
                "ok so i finally tried that new ramen place downtown and honestly? "
                "underwhelming. the broth was fine but they put WAY too much sodium in it and "
                "i was thirsty for like three hours after. my friend got the spicy version and "
                "said it was better. probably won't go back unless someone drags me there"
            ),
        ),
        (
            "Borderline",
            (
                "I've been thinking a lot about remote work lately. There are genuine tradeoffs "
                "— flexibility and no commute on one side, isolation and blurred work-life "
                "boundaries on the other. Studies show productivity varies widely by individual "
                "and role type."
            ),
        ),
    ]

    for label, text in tests:
        score = get_llm_score(text)
        if score is not None:
            attribution, confidence = classify(score)
            print(f"{label:15s} score={score:.3f}  attribution={attribution:12s}  confidence={confidence:.4f}")
        else:
            print(f"{label:15s} PARSE FAILURE")
