import json
import os
import re
import string

from groq import Groq

_client: Groq | None = None


def _get_client() -> Groq:
    global _client
    if _client is None:
        _client = Groq(api_key=os.environ.get("GROQ_API_KEY"))
    return _client


_SYSTEM_PROMPT = (
    "You are an AI content classifier. Analyze the text provided and assess how likely "
    "it is to have been generated by an AI model rather than written by a human.\n\n"
    "Return ONLY a JSON object with this exact format:\n"
    '{\"score\": X.XX}\n\n'
    "Where X.XX is a float between 0.0 and 1.0:\n"
    "- 0.0 = definitely human-written\n"
    "- 1.0 = definitely AI-generated\n\n"
    "Consider: uniformity of sentence structure, presence of hedging or filler phrases "
    "(\"it is important to note\", \"furthermore\", \"in conclusion\"), absence of personal "
    "voice or idiosyncratic word choices, and overall stylistic consistency. "
    "Do not include any explanation — only the JSON object."
)


def get_llm_score(text: str) -> float | None:
    """Return AI-likeness score 0.0–1.0, or None on parse failure. Raises on API/network error."""
    response = _get_client().chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": _SYSTEM_PROMPT},
            {"role": "user", "content": f"Text to analyze:\n---\n{text}\n---"},
        ],
        temperature=0.0,
        max_tokens=20,
    )
    raw = response.choices[0].message.content.strip()
    try:
        data = json.loads(raw)
        score = float(data["score"])
        return max(0.0, min(1.0, score))
    except (json.JSONDecodeError, KeyError, ValueError, TypeError) as e:
        print(f"[WARN] get_llm_score parse failure: {e!r} | raw={raw!r}", flush=True)
        return None


def classify(raw_score: float) -> tuple[str, float]:
    """Map raw_score to (attribution, confidence) per spec thresholds.

    MS3: called with signal_1_score.
    MS4: called with weighted raw_score = 0.6*s1 + 0.4*s2 — thresholds unchanged.
    """
    if raw_score >= 0.70:
        attribution = "likely_ai"
    elif raw_score <= 0.30:
        attribution = "likely_human"
    else:
        attribution = "uncertain"
    confidence = round(0.5 + abs(raw_score - 0.5), 4)
    return attribution, confidence


def get_stylometric_score(text: str) -> float:
    """Return structural AI-likeness score 0.0–1.0. Pure Python, never raises.

    Three sub-metrics averaged; 1.0 = maximally AI-like, 0.0 = maximally human-like.
    Sentence-length variance is the dominant signal; TTR is the weakest (see inline note).
    """
    # Sub-metric 1: Sentence-length variance
    # Low variance = AI-like (uniform sentence lengths) → high sub_score
    sentences = [s.strip() for s in re.split(r'[.!?]+', text) if s.strip()]
    if len(sentences) < 3:
        sent_var_score = 0.5  # neutral — too few sentences for reliable variance
    else:
        lengths = [len(s.split()) for s in sentences]
        mean = sum(lengths) / len(lengths)
        variance = sum((l - mean) ** 2 for l in lengths) / len(lengths)
        MAX_VAR = 100.0
        sent_var_score = 1.0 - min(variance, MAX_VAR) / MAX_VAR

    # Sub-metric 2: Type-token ratio (TTR)
    # High TTR = diverse vocabulary = human-like → low sub_score.
    # TTR is the weakest sub-metric: for texts under ~80 words, TTR saturates toward 1.0
    # regardless of authorship, so it can mildly mis-vote on short AI text (scoring it
    # slightly human-like). Retained per spec; sentence-length variance carries most signal.
    tokens = re.findall(r'\b\w+\b', text.lower())
    if len(tokens) < 20:
        ttr_score = 0.5  # neutral — too few tokens for reliable TTR
    else:
        ttr = len(set(tokens)) / len(tokens)
        ttr_score = 1.0 - ttr

    # Sub-metric 3: Punctuation density
    # Low density = AI-like (standard minimal punctuation) → high sub_score
    if not text:
        punct_score = 0.5
    else:
        punct_count = sum(1 for c in text if c in string.punctuation)
        density = punct_count / len(text)
        MAX_DENSITY = 0.10
        punct_score = 1.0 - min(density, MAX_DENSITY) / MAX_DENSITY

    return round((sent_var_score + ttr_score + punct_score) / 3.0, 4)


def combine_scores(s1: float, s2: float) -> float:
    """Weighted combination: LLM 60%, stylometrics 40%, per planning.md spec."""
    return round(0.60 * s1 + 0.40 * s2, 4)


if __name__ == "__main__":
    from dotenv import load_dotenv

    load_dotenv()

    tests = [
        (
            "Clearly AI",
            (
                "Artificial intelligence represents a transformative paradigm shift in modern "
                "society. It is important to note that while the benefits of AI are numerous, "
                "it is equally essential to consider the ethical implications. Furthermore, "
                "stakeholders across various sectors must collaborate to ensure responsible "
                "deployment."
            ),
        ),
        (
            "Clearly human",
            (
                "ok so i finally tried that new ramen place downtown and honestly? "
                "underwhelming. the broth was fine but they put WAY too much sodium in it and "
                "i was thirsty for like three hours after. my friend got the spicy version and "
                "said it was better. probably won't go back unless someone drags me there"
            ),
        ),
        (
            "Formal human",
            (
                "The relationship between monetary policy and asset price inflation has been "
                "extensively studied in the literature. Central banks face a fundamental tension "
                "between their mandate for price stability and the unintended consequences of "
                "prolonged low interest rates on equity and real estate valuations."
            ),
        ),
        (
            "Borderline",
            (
                "I've been thinking a lot about remote work lately. There are genuine tradeoffs "
                "— flexibility and no commute on one side, isolation and blurred work-life "
                "boundaries on the other. Studies show productivity varies widely by individual "
                "and role type."
            ),
        ),
    ]

    print(f"{'Sample':<16} {'s1':>6} {'s2':>6} {'raw':>6} {'attribution':<14} {'confidence':>10}")
    print("-" * 66)
    for label, text in tests:
        s2 = get_stylometric_score(text)
        s1 = get_llm_score(text)
        if s1 is not None:
            raw = combine_scores(s1, s2)
            attribution, confidence = classify(raw)
            print(f"{label:<16} {s1:>6.3f} {s2:>6.3f} {raw:>6.3f} {attribution:<14} {confidence:>10.4f}")
        else:
            print(f"{label:<16} {'PARSE FAILURE':>40}")
